name: 'setup-artifact-version'
description: 'Set up artifact version'
branding:
  icon: git-commit
  color: blue
author: 'coscene.io'
inputs:
  customizedVersion: # change this
    required: false
    description: 'Customized version to override the default implementation with tag/commitId'
outputs:
  version:
    description: 'The version of the artifact'
runs:
  using: 'node16'
  main: 'dist/index.js'
